# Generated by Django 5.2.11 on 2026-04-06 07:50

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=core.models._gen_uid, editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('kyc_level', models.PositiveSmallIntegerField(default=0)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('BUSINESS', 'Business')], default='BASIC', max_length=12)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('_credit_score', models.PositiveSmallIntegerField(db_column='c_scr', default=300)),
                ('_risk_band', models.PositiveSmallIntegerField(db_column='r_bnd', default=3)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'sp_usr',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('to_currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('_rate_micro', models.BigIntegerField(db_column='rate_mu')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sp_fx',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(default=core.models._gen_wallet_ref, editable=False, max_length=24, unique=True)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', max_length=3)),
                ('_balance_micro', models.BigIntegerField(db_column='bal_mu', default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sp_wlt',
                'unique_together': {('owner', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(default=core.models._gen_savings_ref, editable=False, max_length=24, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🎯', max_length=8)),
                ('_target_micro', models.BigIntegerField(db_column='tgt_mu')),
                ('_current_micro', models.BigIntegerField(db_column='cur_mu', default=0)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('auto_save', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='M', max_length=1)),
                ('_auto_amount_micro', models.BigIntegerField(db_column='aa_mu', default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_goals', to='core.wallet')),
            ],
            options={
                'db_table': 'sp_sav',
            },
        ),
        migrations.CreateModel(
            name='MicroLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(default=core.models._gen_loan_ref, editable=False, max_length=24, unique=True)),
                ('_principal_micro', models.BigIntegerField(db_column='prin_mu')),
                ('_outstanding_micro', models.BigIntegerField(db_column='out_mu')),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('interest_bps', models.PositiveIntegerField(default=250)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('REPAID', 'Fully Repaid'), ('DEFAULTED', 'Defaulted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('_score_snapshot', models.PositiveSmallIntegerField(db_column='scr_snap', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('repaid_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.wallet')),
            ],
            options={
                'db_table': 'sp_ln',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(default=core.models._gen_txn_ref, editable=False, max_length=34, unique=True)),
                ('txn_type', models.CharField(choices=[('SEND', 'Send Money'), ('RECEIVE', 'Receive Money'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('LOAN_CREDIT', 'Loan Disbursement'), ('LOAN_DEBIT', 'Loan Repayment'), ('SAVINGS_IN', 'Savings Deposit'), ('SAVINGS_OUT', 'Savings Withdrawal'), ('FEE', 'Service Fee'), ('REVERSAL', 'Transaction Reversal')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=12)),
                ('_amount_micro', models.BigIntegerField(db_column='amt_mu')),
                ('_fee_micro', models.BigIntegerField(db_column='fee_mu', default=0)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('counterparty_ref', models.CharField(blank=True, max_length=128)),
                ('counterparty_label', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.wallet')),
            ],
            options={
                'db_table': 'sp_txn',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'status'], name='sp_txn_wallet__947304_idx'), models.Index(fields=['ref'], name='sp_txn_ref_00db4f_idx')],
            },
        ),
    ]
